version: 2
jobs:
  build:
    docker:
       - image: circleci/buildpack-deps:14.04

    steps:
      - checkout
      
      - setup_remote_docker
      
      - run:
          name: Install Docker Compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.19.0/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose                

      - run:
          name: Build
          command: |
            set -x
            docker-compose build
            

      - run:
          name: Test
          command: |            
            chmod +x /usr/local/bin/client.sh 
            docker-compose run client
