version: 2
jobs:
  build:
    docker:
      - image: circleci/build-image:ubuntu-14.04-XL-922-9410082

    steps:
      - checkout

      - run:
          name: Build
          command: docker-compose build

      - run:
          name: Test
          command: docker-compose run client
