version: 2
jobs:
  build:
    docker:
       - image: circleci/cci-demo-docker-primary:0.0.2

    steps:
      - checkout
      
      - setup_remote_docker
      
      - run:
          name: Install Docker Compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.19.0/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose                

      - run:
          name: Build
          command: |
            docker-compose build

      - run:
          name: Test
          command: docker-compose run client
