version: 2
jobs:
  build:
    docker:
      - image: debian:stretch

    steps:
      - checkout

      - run:
          name: Build
          command: docker-compose build

      - run:
          name: Test
          command: docker-compose run client
